package com.filamentvault.domain.model

import com.filamentvault.data.local.entity.FilamentEntity

data class Filament(
    val id: Long = 0,
    val materialType: String,
    val colorHex: String,
    val fillType: String? = null,
    val colorName: String? = null,
    val brand: String? = null,
    val filamentDiameter: Float = 1.75f,
    val nozzleTempMin: Int? = null,
    val nozzleTempMax: Int? = null,
    val bedTempMin: Int? = null,
    val bedTempMax: Int? = null,
    val chamberTemp: Int? = null,
    val printSpeedMin: Int? = null,
    val printSpeedMax: Int? = null,
    val maxVolumetricSpeed: Float? = null,
    val fanSpeedMin: Int? = null,
    val fanSpeedMax: Int? = null,
    val fanSpeedNotes: String? = null,
    val retractionDistance: Float? = null,
    val retractionSpeed: Float? = null,
    val flowRate: Float? = null,
    val layerHeightMin: Float? = null,
    val layerHeightMax: Float? = null,
    val density: Float? = null,
    val dryingTemp: Int? = null,
    val dryingTime: Int? = null,
    val moistureSensitivity: String? = null,
    val quantity: Int = 1,
    val notes: String? = null,
    val imageUri: String? = null,
    val originalImageUri: String? = null,
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis()
) {
    fun toEntity(): FilamentEntity = FilamentEntity(
        id = id,
        materialType = materialType,
        colorHex = colorHex,
        fillType = fillType,
        colorName = colorName,
        brand = brand,
        filamentDiameter = filamentDiameter,
        nozzleTempMin = nozzleTempMin,
        nozzleTempMax = nozzleTempMax,
        bedTempMin = bedTempMin,
        bedTempMax = bedTempMax,
        chamberTemp = chamberTemp,
        printSpeedMin = printSpeedMin,
        printSpeedMax = printSpeedMax,
        maxVolumetricSpeed = maxVolumetricSpeed,
        fanSpeedMin = fanSpeedMin,
        fanSpeedMax = fanSpeedMax,
        fanSpeedNotes = fanSpeedNotes,
        retractionDistance = retractionDistance,
        retractionSpeed = retractionSpeed,
        flowRate = flowRate,
        layerHeightMin = layerHeightMin,
        layerHeightMax = layerHeightMax,
        density = density,
        dryingTemp = dryingTemp,
        dryingTime = dryingTime,
        moistureSensitivity = moistureSensitivity,
        quantity = quantity,
        notes = notes,
        imageUri = imageUri,
        originalImageUri = originalImageUri,
        createdAt = createdAt,
        updatedAt = updatedAt
    )

    companion object {
        fun fromEntity(entity: FilamentEntity): Filament = Filament(
            id = entity.id,
            materialType = entity.materialType,
            colorHex = entity.colorHex,
            fillType = entity.fillType,
            colorName = entity.colorName,
            brand = entity.brand,
            filamentDiameter = entity.filamentDiameter,
            nozzleTempMin = entity.nozzleTempMin,
            nozzleTempMax = entity.nozzleTempMax,
            bedTempMin = entity.bedTempMin,
            bedTempMax = entity.bedTempMax,
            chamberTemp = entity.chamberTemp,
            printSpeedMin = entity.printSpeedMin,
            printSpeedMax = entity.printSpeedMax,
            maxVolumetricSpeed = entity.maxVolumetricSpeed,
            fanSpeedMin = entity.fanSpeedMin,
            fanSpeedMax = entity.fanSpeedMax,
            fanSpeedNotes = entity.fanSpeedNotes,
            retractionDistance = entity.retractionDistance,
            retractionSpeed = entity.retractionSpeed,
            flowRate = entity.flowRate,
            layerHeightMin = entity.layerHeightMin,
            layerHeightMax = entity.layerHeightMax,
            density = entity.density,
            dryingTemp = entity.dryingTemp,
            dryingTime = entity.dryingTime,
            moistureSensitivity = entity.moistureSensitivity,
            quantity = entity.quantity,
            notes = entity.notes,
            imageUri = entity.imageUri,
            originalImageUri = entity.originalImageUri,
            createdAt = entity.createdAt,
            updatedAt = entity.updatedAt
        )
    }
}
